spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related production APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}485c1506fcc5eb9240ce16642383f1bc142d3b2c4eb333a16bcb87f90bb4ccf89275207db25a33a1b524cf0c5d809621"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
